export const INTERVIEW_STATUS = Object.freeze({
  CREATED: 'CREATED',
  READY: 'READY',
  IN_PROGRESS: 'IN_PROGRESS',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED'
});

export const INTERVIEW_STATUS_LABELS = Object.freeze({
  [INTERVIEW_STATUS.CREATED]: 'Created',
  [INTERVIEW_STATUS.READY]: 'Ready to Start',
  [INTERVIEW_STATUS.IN_PROGRESS]: 'In Progress',
  [INTERVIEW_STATUS.PAUSED]: 'Paused',
  [INTERVIEW_STATUS.COMPLETED]: 'Completed',
  [INTERVIEW_STATUS.ABANDONED]: 'Abandoned'
});
