import React, { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import apiClient from '../../api/apiClient.js';
import {
  Award,
  CheckCircle2,
  AlertCircle,
  Clock,
  Sparkles,
  Bot,
  Printer,
  ChevronDown,
  ChevronUp,
  Check,
  Lightbulb,
  RefreshCw,
  ExternalLink
} from 'lucide-react';

export const SharedReportPage = () => {
  const { shareToken } = useParams();
  const [expandedIndex, setExpandedIndex] = useState(null);

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['sharedInterviewReport', shareToken],
    queryFn: async () => {
      const res = await apiClient.get(`/interviews/shared/${shareToken}`);
      return res.data;
    },
    refetchOnWindowFocus: false
  });

  if (isLoading) {
    return (
      <div className="flex min-h-[60vh] flex-col items-center justify-center space-y-4">
        <RefreshCw className="h-8 w-8 animate-spin text-brand-600" />
        <p className="text-sm font-medium text-slate-500 dark:text-slate-400">
          Loading verified interview report...
        </p>
      </div>
    );
  }

  if (isError || !data?.report) {
    return (
      <div className="max-w-md mx-auto my-16 p-8 rounded-3xl border border-red-200 bg-red-50 text-center dark:border-red-900 dark:bg-red-950/30 space-y-3">
        <AlertCircle className="mx-auto h-10 w-10 text-red-600 mb-2" />
        <h2 className="text-base font-bold text-red-900 dark:text-red-200">Shared Report Unavailable</h2>
        <p className="text-xs text-red-700 dark:text-red-400">
          {error?.message || 'This shared report link does not exist or has been revoked by the owner.'}
        </p>
        <Link
          to="/"
          className="mt-3 inline-block rounded-xl bg-brand-600 px-4 py-2 text-xs font-semibold text-white"
        >
          Go to InterviewAI Homepage
        </Link>
      </div>
    );
  }

  const { report, interview, questionBreakdown = [] } = data;
  const dimensionScores = report.dimensionScores || {};

  const getScoreColor = (score) => {
    if (score >= 80) return 'text-emerald-600 dark:text-emerald-400';
    if (score >= 65) return 'text-amber-600 dark:text-amber-400';
    return 'text-red-600 dark:text-red-400';
  };

  const getScoreBg = (score) => {
    if (score >= 80) return 'bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-300 dark:border-emerald-900';
    if (score >= 65) return 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/50 dark:text-amber-300 dark:border-amber-900';
    return 'bg-red-50 text-red-700 border-red-200 dark:bg-red-950/50 dark:text-red-300 dark:border-red-900';
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8 print:py-0 print:px-0">
      {/* Verified Banner for Public Viewers */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 rounded-2xl bg-gradient-to-r from-brand-900 to-slate-900 p-4 text-white shadow-md print:hidden">
        <div className="flex items-center space-x-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600">
            <Bot className="h-5 w-5" />
          </div>
          <div>
            <span className="text-xs font-bold block">Verified Candidate Scorecard</span>
            <span className="text-[11px] text-slate-300">Generated by InterviewAI Evaluation Engine</span>
          </div>
        </div>
        <div className="flex items-center space-x-3">
          <button
            onClick={() => window.print()}
            className="inline-flex items-center rounded-xl bg-white/10 hover:bg-white/20 px-3 py-1.5 text-xs font-semibold text-white transition"
          >
            <Printer className="mr-1.5 h-3.5 w-3.5" /> Print / Export PDF
          </button>
          <Link
            to="/register"
            className="inline-flex items-center rounded-xl bg-brand-600 px-3.5 py-1.5 text-xs font-bold text-white hover:bg-brand-700 transition"
          >
            Try InterviewAI Free <ExternalLink className="ml-1 h-3 w-3" />
          </Link>
        </div>
      </div>

      {/* Header Info */}
      <div className="space-y-1">
        <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">
          {interview.title}
        </h1>
        <p className="text-xs text-slate-500 dark:text-slate-400">
          Target: {interview.targetRole} at {interview.targetCompany} • {interview.difficulty} Difficulty • {new Date(report.generatedAt).toLocaleDateString()}
        </p>
      </div>

      {/* Scorecard Hero */}
      <div className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
          <div className="flex flex-col items-center justify-center p-4 border-b md:border-b-0 md:border-r border-slate-100 dark:border-slate-800">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2">Overall Score</span>
            <div className={`flex h-28 w-28 items-center justify-center rounded-full border-4 ${
              report.overallScore >= 80 ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/40' :
              report.overallScore >= 65 ? 'border-amber-500 bg-amber-50 dark:bg-amber-950/40' :
              'border-red-500 bg-red-50 dark:bg-red-950/40'
            }`}>
              <span className={`text-3xl font-extrabold ${getScoreColor(report.overallScore)}`}>
                {report.overallScore}
              </span>
              <span className="text-xs text-slate-400 font-bold self-end mb-4">/100</span>
            </div>
            <span className={`mt-3 inline-flex items-center rounded-full px-3 py-0.5 text-xs font-bold border ${getScoreBg(report.overallScore)}`}>
              {report.overallScore >= 80 ? 'High Readiness' : report.overallScore >= 65 ? 'Moderate Readiness' : 'Needs Practice'}
            </span>
          </div>

          <div className="md:col-span-2 space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">
              Performance Dimensions
            </h3>
            {[
              { label: 'Technical Correctness', val: dimensionScores.correctness || 0 },
              { label: 'Question Relevance', val: dimensionScores.relevance || 0 },
              { label: 'Answer Completeness', val: dimensionScores.completeness || 0 },
              { label: 'Communication & Structure', val: dimensionScores.communication || 0 },
              { label: 'Clarity & Delivery', val: dimensionScores.clarity || 0 }
            ].map((dim, idx) => (
              <div key={idx} className="space-y-1">
                <div className="flex justify-between text-xs font-semibold">
                  <span className="text-slate-700 dark:text-slate-300">{dim.label}</span>
                  <span className={getScoreColor(dim.val)}>{dim.val}%</span>
                </div>
                <div className="h-2 w-full rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden">
                  <div
                    className={`h-full rounded-full ${dim.val >= 80 ? 'bg-emerald-500' : dim.val >= 65 ? 'bg-amber-500' : 'bg-red-500'}`}
                    style={{ width: `${dim.val}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Question-by-Question Breakdown */}
      <div className="space-y-4">
        <h2 className="text-lg font-bold text-slate-900 dark:text-white">
          Question Responses & Evaluation
        </h2>

        <div className="space-y-4">
          {questionBreakdown.map((item, index) => {
            const isExpanded = expandedIndex === index || true; // Expand by default for readability in shared/print
            const evalData = item.evaluation;
            const answerData = item.answer;

            return (
              <div
                key={index}
                className="rounded-3xl border border-slate-200 bg-white overflow-hidden shadow-sm dark:border-slate-800 dark:bg-slate-900"
              >
                <div className="p-6 space-y-3">
                  <div className="flex items-center space-x-2">
                    <span className="rounded-md bg-slate-100 px-2 py-0.5 text-[11px] font-bold text-slate-700 dark:bg-slate-800 dark:text-slate-300">
                      Q{index + 1} • {item.category}
                    </span>
                    {evalData && (
                      <span className={`rounded-full px-2 py-0.5 text-[10px] font-bold border ${getScoreBg(evalData.overallScore)}`}>
                        Score: {evalData.overallScore}/100
                      </span>
                    )}
                  </div>

                  <h3 className="text-base font-bold text-slate-900 dark:text-white">
                    {item.questionText}
                  </h3>

                  <div className="rounded-2xl bg-slate-50 p-4 border border-slate-100 dark:border-slate-800 dark:bg-slate-950/40 space-y-1">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">Candidate Transcript</span>
                    <p className="text-xs text-slate-800 dark:text-slate-200 whitespace-pre-wrap leading-relaxed">
                      {answerData?.isSkipped ? '[Skipped]' : answerData?.transcriptText || '[No answer recorded]'}
                    </p>
                  </div>

                  {evalData && (
                    <div className="space-y-3 pt-2">
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <div className="rounded-xl bg-emerald-50/50 p-3 border border-emerald-100 dark:border-emerald-950 dark:bg-emerald-950/20 text-xs space-y-1">
                          <span className="font-bold text-emerald-700 dark:text-emerald-400 block">Strengths</span>
                          {evalData.strengths?.map((s, i) => (
                            <p key={i} className="text-slate-700 dark:text-slate-300">• {s}</p>
                          ))}
                        </div>
                        <div className="rounded-xl bg-amber-50/50 p-3 border border-amber-100 dark:border-amber-950 dark:bg-amber-950/20 text-xs space-y-1">
                          <span className="font-bold text-amber-700 dark:text-amber-400 block">Feedback</span>
                          {evalData.feedback?.map((f, i) => (
                            <p key={i} className="text-slate-700 dark:text-slate-300">• {f}</p>
                          ))}
                        </div>
                      </div>

                      {evalData.idealAnswer && (
                        <div className="rounded-xl bg-brand-50/40 p-3 border border-brand-100 dark:border-brand-950 dark:bg-brand-950/20 text-xs space-y-1">
                          <span className="font-bold text-brand-700 dark:text-brand-400 block">Ideal Answer Guide</span>
                          <p className="text-slate-700 dark:text-slate-300 whitespace-pre-wrap leading-relaxed">{evalData.idealAnswer}</p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default SharedReportPage;
